import '@servicenow/sdk/global';
import { Record } from '@servicenow/sdk/core';

export const sapEq1 = Record({
    $id: Now.ID['sap-eq-0000457'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010000457',
        equipment_desc: 'Haul Truck 793F #04',
        equipment_category: 'vehicle',
        object_type: 'Haul Truck',
        manufacturer: 'Caterpillar',
        model_number: '793F',
        serial_number: 'CAT793F-7XR04521',
        manufacture_year: '2019',
        cost_centre: '4410220000',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-MINE-FLEET-HT04',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq2 = Record({
    $id: Now.ID['sap-eq-0000981'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010000981',
        equipment_desc: 'HAUL TRUCK 793F 04',
        equipment_category: 'vehicle',
        object_type: 'Haul Truck',
        manufacturer: 'CATERPILLAR INC',
        model_number: '793F',
        serial_number: 'CAT793F-7XR04521',
        manufacture_year: '2019',
        cost_centre: '4410220000',
        maintenance_plant: '2020',
        planning_plant: '2020',
        functional_location: 'GLD-PORT-FLEET-HT04',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq3 = Record({
    $id: Now.ID['sap-eq-0001120'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010001120',
        equipment_desc: 'Excavator PC8000 #02',
        equipment_category: 'machine',
        object_type: 'Hydraulic Excavator',
        manufacturer: 'Komatsu',
        model_number: 'PC8000-6',
        serial_number: 'PC8000-K2291',
        manufacture_year: '2021',
        cost_centre: '4410220000',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-MINE-LOAD-EX02',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq4 = Record({
    $id: Now.ID['sap-eq-0001188'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010001188',
        equipment_desc: 'Excavator PC8000 #02',
        equipment_category: 'machine',
        object_type: 'Hydraulic Excavator',
        manufacturer: 'Komatsu',
        model_number: 'PC8000-6',
        serial_number: 'PC8000-K2219',
        manufacture_year: '2021',
        cost_centre: '4410220000',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-MINE-LOAD-EX02',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq5 = Record({
    $id: Now.ID['sap-eq-0002044'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010002044',
        equipment_desc: 'Slurry Pump Warman 650',
        equipment_category: 'pump',
        object_type: 'Slurry Pump',
        manufacturer: 'Weir Minerals',
        model_number: 'Warman 650MCR',
        serial_number: 'WM650-AU-77310',
        manufacture_year: '2020',
        cost_centre: '4410330000',
        maintenance_plant: '2020',
        planning_plant: '2020',
        functional_location: 'GLD-PROC-PUMP-A1',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq6 = Record({
    $id: Now.ID['sap-eq-0002051'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010002051',
        equipment_desc: 'Slurry Pump Warman 550',
        equipment_category: 'pump',
        object_type: 'Slurry Pump',
        manufacturer: 'Weir',
        model_number: 'Warman 550MCR',
        serial_number: 'WM550-AU-77822',
        manufacture_year: '2020',
        cost_centre: '4410330000',
        maintenance_plant: '2020',
        planning_plant: '2020',
        functional_location: 'GLD-PROC-PUMP-A2',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq7 = Record({
    $id: Now.ID['sap-eq-0002066'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010002066',
        equipment_desc: 'Slurry Pump Warman 450',
        equipment_category: 'pump',
        object_type: 'Slurry Pump',
        manufacturer: 'WEIR MINERALS AUST',
        model_number: 'Warman 450MCR',
        serial_number: 'WM450-AU-77930',
        manufacture_year: '2022',
        cost_centre: '4410330000',
        maintenance_plant: '2020',
        planning_plant: '2020',
        functional_location: 'GLD-PROC-PUMP-A3',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq8 = Record({
    $id: Now.ID['sap-eq-0003012'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010003012',
        equipment_desc: 'Power Transformer 33kV',
        equipment_category: 'electrical',
        object_type: 'Power Transformer',
        manufacturer: 'ABB',
        model_number: 'TXN-33-2500',
        serial_number: 'ABB-33-220041',
        manufacture_year: '2018',
        cost_centre: '',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-SUB-TX-01',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq9 = Record({
    $id: Now.ID['sap-eq-0003110'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010003110',
        equipment_desc: 'Conveyor Drive CV-12',
        equipment_category: 'conveyor',
        object_type: 'Belt Conveyor',
        manufacturer: 'Sandvik',
        model_number: 'CV-DRIVE-1200',
        serial_number: 'SDV-CV12-5567',
        manufacture_year: '2015',
        cost_centre: 'CC-4410',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-PROC-CONV-12',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq10 = Record({
    $id: Now.ID['sap-eq-0003598'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010003598',
        equipment_desc: 'Conveyor Drive CV-03 (OLD)',
        equipment_category: 'conveyor',
        object_type: 'Belt Conveyor',
        manufacturer: 'Sandvik',
        model_number: 'CV-DRIVE-800',
        serial_number: 'SDV-CV03-1102',
        manufacture_year: '2009',
        cost_centre: '4410330000',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-PROC-CONV-03',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '2019-12-31',
        sap_status: 'deletion_flag',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq11 = Record({
    $id: Now.ID['sap-eq-0004001'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010004001',
        equipment_desc: 'Dragline BE 1370W',
        equipment_category: 'machine',
        object_type: 'Walking Dragline',
        manufacturer: 'Bucyrus-Erie',
        model_number: '1370W',
        serial_number: 'BE1370-DL-0009',
        manufacture_year: '2011',
        cost_centre: '4410220000',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-MINE-DRAG-01',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq12 = Record({
    $id: Now.ID['sap-eq-0004220'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010004220',
        equipment_desc: 'Loader 994K #01',
        equipment_category: 'vehicle',
        object_type: 'Wheel Loader',
        manufacturer: 'Caterpillar',
        model_number: '994K',
        serial_number: 'CAT994K-LL00231',
        manufacture_year: '2020',
        cost_centre: '4410220000',
        maintenance_plant: '2010',
        planning_plant: '2010',
        functional_location: 'MKO-MINE-LOAD-WL01',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});

export const sapEq13 = Record({
    $id: Now.ID['sap-eq-0004388'],
    table: 'x_snc_eqmdm_sap_equipment',
    data: {
        sap_equipment_no: '000000010004388',
        equipment_desc: 'Cooling Pump CP-7',
        equipment_category: 'pump',
        object_type: 'Centrifugal Pump',
        manufacturer: 'Grundfos',
        model_number: 'NK-200-400',
        serial_number: 'GF-NK200-88123',
        manufacture_year: '2023',
        cost_centre: '4410330000',
        maintenance_plant: '2020',
        planning_plant: '2020',
        functional_location: 'GLD-PROC-PUMP-B7',
        company_code: '1000',
        currency: 'AUD',
        valid_to: '9999-12-31',
        sap_status: 'active',
        ingestion_status: 'not_ingested',
    },
});
